{
    "name"          : "New Addons",
    "version"       : "1.0",
    "Author"        : "Dwiary Putri Megayanti",
    "website"       : "https://www.kompas.com",
    "category"      : "New Modul",
    "summary"       : "Ini adalah addons baru",
    "description"   : """Latihan Membuat addons baru di odoo 1""",
    "depends"       : ["base"],
    "data"          : [],
    "demo"          : [],
    "test"          : [],
    "images"        : [],
    "qweb"          : [],
    "css"           : [],
    "application"   : True,
    "installable"   : True,
    "auto_install"  : False,
    
}